# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kanban-desk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: npm install, build, and test
        run: |
          cd server
          npm install
          npm install -g @nestjs/cli
          npm install -g jest
          npm i -g typeorm
          npm i -g ts-node
          npm run build --if-present
          npm run test --if-present
          cd ../client
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5AC3F3CD9D0C4ACAB8ED4FFA891B22D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_19DDC1F8896A4EE6949E2D535E1C2272 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C4683613699A4C5CA62D74BDD61CB171 }}    

      - name: Deploy database
        env:
          AZURE_SQL_DATABASE: ${{secrets.AZURE_SQL_DATABASE}}
          AZURE_SQL_SERVER: ${{secrets.AZURE_SQL_SERVER}}
          AZURE_SQL_USERNAME: ${{secrets.AZURE_SQL_USERNAME}}
          AZURE_SQL_PASSWORD: ${{secrets.AZURE_SQL_PASSWORD}}
          AZURE_SQL_PORT: ${{secrets.AZURE_SQL_PORT}}
        run: |
          az sql server firewall-rule create --resource-group Kanban --server $AZURE_SQL_SERVER --name GithubAction --start-ip-address ${{ steps.ip.outputs.ipv4 }} --end-ip-address ${{ steps.ip.outputs.ipv4 }}
          cd server
          npm run migration:run
          az sql server firewall-rule delete --resource-group Kanban --server $AZURE_SQL_SERVER --name GithubAction

      - name: Prepare deployment artifact
        run: |
          mv server/node_modules server/dist/node_modules
          mv client/dist server/dist/client

      - name: Zip artifact for deployment
        run: zip release.zip ./server/dist/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5AC3F3CD9D0C4ACAB8ED4FFA891B22D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_19DDC1F8896A4EE6949E2D535E1C2272 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C4683613699A4C5CA62D74BDD61CB171 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kanban-desk'
          slot-name: 'Production'
          package: .
          
